"""Curated recipe catalog for the discovery screen.

Recipes are matched to the user's goals (calorie budget + goal direction)
in server.py; this module only holds the data.
"""

from typing import List, Dict, Any


def _u(photo_id: str) -> str:
    return f"https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=900&q=80"


RECIPE_CATEGORIES = [
    {"id": "All", "image": _u("photo-1546069901-ba9599a7e63c")},
    {"id": "Vegan", "image": _u("photo-1512621776951-a57141f2eefd")},
    {"id": "Protein", "image": _u("photo-1467003909585-2f8a72700288")},
    {"id": "Snacks", "image": _u("photo-1568901346375-23c9450c58cd")},
    {"id": "Sweets", "image": _u("photo-1567620905732-2d1ec7ab7445")},
]


RECIPES: List[Dict[str, Any]] = [
    {
        "id": "quinoa-veggie-bowl",
        "title": "Quinoa Veggie Bowl",
        "minutes": 45,
        "difficulty": 2,
        "difficulty_label": "Medium",
        "category": "Vegan",
        "image": _u("photo-1512621776951-a57141f2eefd"),
        "kcal": 520,
        "protein_g": 18,
        "carbs_g": 74,
        "fat_g": 16,
        "fiber_g": 12,
        "description": "A hearty bowl of fluffy quinoa, roasted seasonal vegetables and a lemon-tahini drizzle.",
        "ingredients": [
            "1 cup quinoa, rinsed",
            "1 zucchini, diced",
            "1 red bell pepper, sliced",
            "1 cup chickpeas, cooked",
            "2 tbsp tahini",
            "1 lemon, juiced",
            "2 tsp olive oil",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Cook quinoa in 2 cups of water for 15 minutes, then fluff with a fork.",
            "Roast zucchini and bell pepper with olive oil at 200°C for 20 minutes.",
            "Whisk tahini with lemon juice and 2 tbsp water into a dressing.",
            "Assemble quinoa, vegetables and chickpeas in a bowl; drizzle with dressing.",
        ],
    },
    {
        "id": "grilled-salmon-bowl",
        "title": "Grilled Salmon Bowl",
        "minutes": 35,
        "difficulty": 2,
        "difficulty_label": "Medium",
        "category": "Protein",
        "image": _u("photo-1467003909585-2f8a72700288"),
        "kcal": 620,
        "protein_g": 42,
        "carbs_g": 48,
        "fat_g": 26,
        "fiber_g": 6,
        "description": "Charred salmon fillet over brown rice with edamame, avocado and a soy-ginger glaze.",
        "ingredients": [
            "180 g salmon fillet",
            "3/4 cup brown rice, cooked",
            "1/2 avocado, sliced",
            "1/2 cup edamame, shelled",
            "1 tbsp soy sauce",
            "1 tsp grated ginger",
            "1 tsp honey",
            "Sesame seeds for garnish",
        ],
        "steps": [
            "Mix soy sauce, ginger and honey into a glaze; brush over the salmon.",
            "Grill salmon 4–5 minutes per side until it flakes easily.",
            "Arrange rice, edamame and avocado in a bowl.",
            "Top with salmon, spoon over remaining glaze and sprinkle sesame seeds.",
        ],
    },
    {
        "id": "rainbow-crunch-salad",
        "title": "Rainbow Crunch Salad",
        "minutes": 20,
        "difficulty": 1,
        "difficulty_label": "Easy",
        "category": "Vegan",
        "image": _u("photo-1546069901-ba9599a7e63c"),
        "kcal": 380,
        "protein_g": 12,
        "carbs_g": 42,
        "fat_g": 18,
        "fiber_g": 10,
        "description": "Crisp shredded veggies with toasted seeds and a bright apple-cider vinaigrette.",
        "ingredients": [
            "2 cups shredded red cabbage",
            "1 carrot, julienned",
            "1 cup baby spinach",
            "1/2 cup corn kernels",
            "2 tbsp pumpkin seeds, toasted",
            "1 tbsp olive oil",
            "1 tbsp apple cider vinegar",
            "1 tsp maple syrup",
        ],
        "steps": [
            "Toss cabbage, carrot, spinach and corn in a large bowl.",
            "Whisk olive oil, vinegar and maple syrup into a vinaigrette.",
            "Dress the salad and top with toasted pumpkin seeds.",
        ],
    },
    {
        "id": "herb-chicken-skewers",
        "title": "Herb Chicken Skewers",
        "minutes": 40,
        "difficulty": 2,
        "difficulty_label": "Medium",
        "category": "Protein",
        "image": _u("photo-1555939594-58d7cb561ad1"),
        "kcal": 460,
        "protein_g": 46,
        "carbs_g": 14,
        "fat_g": 22,
        "fiber_g": 3,
        "description": "Juicy marinated chicken skewers with charred peppers and a yogurt-herb dip.",
        "ingredients": [
            "300 g chicken breast, cubed",
            "1 bell pepper, in chunks",
            "1 red onion, in chunks",
            "2 tbsp olive oil",
            "1 tsp dried oregano",
            "1/2 cup Greek yogurt",
            "1 tbsp chopped fresh dill",
            "1 garlic clove, minced",
        ],
        "steps": [
            "Marinate chicken in olive oil, oregano, salt and pepper for 20 minutes.",
            "Thread chicken, pepper and onion onto skewers.",
            "Grill 12–14 minutes, turning until cooked through.",
            "Stir yogurt with dill and garlic; serve as a dip.",
        ],
    },
    {
        "id": "turkey-lettuce-wraps",
        "title": "Turkey Lettuce Wraps",
        "minutes": 25,
        "difficulty": 1,
        "difficulty_label": "Easy",
        "category": "Protein",
        "image": _u("photo-1604909052743-94e838986d24"),
        "kcal": 340,
        "protein_g": 34,
        "carbs_g": 16,
        "fat_g": 14,
        "fiber_g": 4,
        "description": "Light, low-carb wraps of savoury ground turkey and water chestnuts in crisp lettuce cups.",
        "ingredients": [
            "250 g lean ground turkey",
            "8 butter lettuce leaves",
            "1/2 cup water chestnuts, chopped",
            "2 spring onions, sliced",
            "1 tbsp soy sauce",
            "1 tsp sesame oil",
            "1 garlic clove, minced",
        ],
        "steps": [
            "Brown turkey with garlic in sesame oil for 6–7 minutes.",
            "Stir in water chestnuts, soy sauce and spring onions; cook 2 minutes.",
            "Spoon the filling into lettuce cups and serve warm.",
        ],
    },
    {
        "id": "tofu-stirfry",
        "title": "Crispy Tofu Stir-Fry",
        "minutes": 30,
        "difficulty": 2,
        "difficulty_label": "Medium",
        "category": "Vegan",
        "image": _u("photo-1512058564366-18510be2db19"),
        "kcal": 450,
        "protein_g": 24,
        "carbs_g": 40,
        "fat_g": 20,
        "fiber_g": 7,
        "description": "Golden pan-fried tofu with broccoli and snap peas in a garlicky soy glaze.",
        "ingredients": [
            "300 g firm tofu, cubed",
            "2 cups broccoli florets",
            "1 cup snap peas",
            "2 tbsp soy sauce",
            "1 tbsp cornstarch",
            "1 tbsp vegetable oil",
            "2 garlic cloves, minced",
        ],
        "steps": [
            "Toss tofu in cornstarch and pan-fry until golden on all sides.",
            "Stir-fry broccoli, snap peas and garlic for 4 minutes.",
            "Return tofu to the pan, add soy sauce and toss to glaze.",
        ],
    },
    {
        "id": "smash-burger-sliders",
        "title": "Smash Burger Sliders",
        "minutes": 30,
        "difficulty": 2,
        "difficulty_label": "Easy",
        "category": "Snacks",
        "image": _u("photo-1568901346375-23c9450c58cd"),
        "kcal": 820,
        "protein_g": 40,
        "carbs_g": 58,
        "fat_g": 46,
        "fiber_g": 3,
        "description": "Crispy-edged beef sliders with melted cheddar and quick pickles on soft buns.",
        "ingredients": [
            "300 g ground beef",
            "4 slider buns",
            "4 slices cheddar",
            "1/4 cup dill pickles",
            "1 tbsp mustard",
            "1 tbsp mayonnaise",
            "Salt and pepper",
        ],
        "steps": [
            "Divide beef into 4 balls; smash flat on a hot skillet.",
            "Season, cook 2 minutes, flip and top with cheddar.",
            "Toast buns, spread with mustard-mayo and stack the patties with pickles.",
        ],
    },
    {
        "id": "hummus-veggie-plate",
        "title": "Hummus & Veggie Plate",
        "minutes": 10,
        "difficulty": 1,
        "difficulty_label": "Easy",
        "category": "Snacks",
        "image": _u("photo-1505576399279-565b52d4ac71"),
        "kcal": 280,
        "protein_g": 10,
        "carbs_g": 30,
        "fat_g": 14,
        "fiber_g": 8,
        "description": "Creamy hummus with crunchy raw vegetables and warm pita wedges.",
        "ingredients": [
            "1/2 cup hummus",
            "1 carrot, cut into sticks",
            "1 cucumber, sliced",
            "1/2 red bell pepper, sliced",
            "1 small whole wheat pita",
            "Paprika and olive oil for topping",
        ],
        "steps": [
            "Spoon hummus into a bowl, drizzle with olive oil and dust with paprika.",
            "Warm the pita and cut into wedges.",
            "Arrange vegetables around the hummus and serve.",
        ],
    },
    {
        "id": "greek-yogurt-parfait",
        "title": "Greek Yogurt Parfait",
        "minutes": 10,
        "difficulty": 1,
        "difficulty_label": "Easy",
        "category": "Snacks",
        "image": _u("photo-1488477181946-6428a0291777"),
        "kcal": 320,
        "protein_g": 22,
        "carbs_g": 38,
        "fat_g": 9,
        "fiber_g": 5,
        "description": "Layers of thick Greek yogurt, crunchy granola and fresh berries.",
        "ingredients": [
            "1 cup Greek yogurt",
            "1/3 cup granola",
            "1/2 cup mixed berries",
            "1 tsp honey",
            "1 tbsp chia seeds",
        ],
        "steps": [
            "Layer half the yogurt, granola and berries in a glass.",
            "Repeat the layers and finish with chia seeds and honey.",
        ],
    },
    {
        "id": "berry-oat-pancakes",
        "title": "Berry Oat Pancakes",
        "minutes": 25,
        "difficulty": 2,
        "difficulty_label": "Easy",
        "category": "Sweets",
        "image": _u("photo-1567620905732-2d1ec7ab7445"),
        "kcal": 480,
        "protein_g": 16,
        "carbs_g": 68,
        "fat_g": 15,
        "fiber_g": 8,
        "description": "Fluffy blender oat pancakes topped with warm berry compote.",
        "ingredients": [
            "1 cup rolled oats",
            "1 banana",
            "2 eggs",
            "1/2 cup milk of choice",
            "1 tsp baking powder",
            "1 cup mixed berries",
            "1 tsp maple syrup",
        ],
        "steps": [
            "Blend oats, banana, eggs, milk and baking powder until smooth.",
            "Cook small pancakes 2 minutes per side over medium heat.",
            "Simmer berries with maple syrup for 3 minutes and spoon over the stack.",
        ],
    },
    {
        "id": "dark-chocolate-energy-bites",
        "title": "Dark Chocolate Energy Bites",
        "minutes": 15,
        "difficulty": 1,
        "difficulty_label": "Easy",
        "category": "Sweets",
        "image": _u("photo-1606313564200-e75d5e30476c"),
        "kcal": 210,
        "protein_g": 7,
        "carbs_g": 24,
        "fat_g": 11,
        "fiber_g": 4,
        "description": "No-bake oat and date bites with dark chocolate chips — per 3-bite serving.",
        "ingredients": [
            "1 cup rolled oats",
            "1/2 cup pitted dates",
            "1/4 cup peanut butter",
            "2 tbsp dark chocolate chips",
            "1 tbsp ground flaxseed",
            "Pinch of sea salt",
        ],
        "steps": [
            "Blitz dates into a paste, then mix with oats, peanut butter and flaxseed.",
            "Fold in chocolate chips and roll into 12 bites.",
            "Chill 30 minutes before serving.",
        ],
    },
    {
        "id": "baked-apple-crumble",
        "title": "Baked Apple Crumble Cups",
        "minutes": 35,
        "difficulty": 2,
        "difficulty_label": "Medium",
        "category": "Sweets",
        "image": _u("photo-1621236378699-8597faf6a176"),
        "kcal": 390,
        "protein_g": 6,
        "carbs_g": 62,
        "fat_g": 14,
        "fiber_g": 7,
        "description": "Cinnamon-spiced baked apples under a golden oat crumble, portioned in ramekins.",
        "ingredients": [
            "2 apples, diced",
            "1 tsp cinnamon",
            "1/2 cup rolled oats",
            "2 tbsp butter, cold",
            "2 tbsp brown sugar",
            "1 tbsp flour",
        ],
        "steps": [
            "Toss apples with cinnamon and divide between two ramekins.",
            "Rub oats, butter, sugar and flour into a crumble.",
            "Top the apples and bake at 190°C for 25 minutes until golden.",
        ],
    },
    {
        "id": "lentil-power-soup",
        "title": "Lentil Power Soup",
        "minutes": 40,
        "difficulty": 2,
        "difficulty_label": "Easy",
        "category": "Vegan",
        "image": _u("photo-1547592166-23ac45744acd"),
        "kcal": 410,
        "protein_g": 22,
        "carbs_g": 58,
        "fat_g": 9,
        "fiber_g": 16,
        "description": "A warming red-lentil soup with carrots, cumin and a squeeze of lemon.",
        "ingredients": [
            "1 cup red lentils, rinsed",
            "1 onion, diced",
            "2 carrots, diced",
            "1 tsp ground cumin",
            "4 cups vegetable stock",
            "1 tbsp olive oil",
            "1/2 lemon, juiced",
        ],
        "steps": [
            "Sauté onion and carrot in olive oil for 5 minutes; add cumin.",
            "Add lentils and stock; simmer 25 minutes until soft.",
            "Blend half the soup for creaminess and finish with lemon juice.",
        ],
    },
    {
        "id": "steak-sweet-potato",
        "title": "Steak & Sweet Potato Mash",
        "minutes": 45,
        "difficulty": 3,
        "difficulty_label": "Hard",
        "category": "Protein",
        "image": _u("photo-1600891964092-4316c288032e"),
        "kcal": 720,
        "protein_g": 48,
        "carbs_g": 52,
        "fat_g": 34,
        "fiber_g": 7,
        "description": "Seared sirloin with garlic butter over silky sweet potato mash and green beans.",
        "ingredients": [
            "220 g sirloin steak",
            "2 sweet potatoes, peeled",
            "1 tbsp butter",
            "1 garlic clove, crushed",
            "150 g green beans",
            "1 tbsp olive oil",
            "Salt and cracked pepper",
        ],
        "steps": [
            "Boil sweet potatoes 15 minutes; mash with half the butter.",
            "Sear the steak 3–4 minutes per side; rest with garlic butter on top.",
            "Steam green beans 4 minutes and plate everything together.",
        ],
    },
    {
        "id": "avocado-toast-eggs",
        "title": "Avocado Toast with Eggs",
        "minutes": 15,
        "difficulty": 1,
        "difficulty_label": "Easy",
        "category": "Snacks",
        "image": _u("photo-1525351484163-7529414344d8"),
        "kcal": 430,
        "protein_g": 19,
        "carbs_g": 34,
        "fat_g": 25,
        "fiber_g": 9,
        "description": "Smashed avocado on toasted sourdough with jammy eggs and chili flakes.",
        "ingredients": [
            "2 slices sourdough bread",
            "1 avocado",
            "2 eggs",
            "1/2 lemon, juiced",
            "Chili flakes and sea salt",
        ],
        "steps": [
            "Boil eggs for 7 minutes, then peel and halve.",
            "Toast the bread and smash avocado with lemon and salt on top.",
            "Add the eggs and finish with chili flakes.",
        ],
    },
    {
        "id": "coconut-chia-pudding",
        "title": "Coconut Chia Pudding",
        "minutes": 10,
        "difficulty": 1,
        "difficulty_label": "Easy",
        "category": "Sweets",
        "image": _u("photo-1541658016709-82535e94bc69"),
        "kcal": 310,
        "protein_g": 9,
        "carbs_g": 28,
        "fat_g": 18,
        "fiber_g": 11,
        "description": "Creamy overnight chia pudding with coconut milk and mango.",
        "ingredients": [
            "3 tbsp chia seeds",
            "1 cup light coconut milk",
            "1 tsp maple syrup",
            "1/2 mango, diced",
            "1 tbsp toasted coconut flakes",
        ],
        "steps": [
            "Whisk chia seeds with coconut milk and maple syrup.",
            "Chill at least 4 hours (or overnight), stirring once.",
            "Top with mango and toasted coconut before serving.",
        ],
    },
]
