import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";

import { api } from "@/src/api";
import { AppScreen } from "@/src/components/AppScreen";
import { PressableScale } from "@/src/components/PressableScale";
import { Toast } from "@/src/components/Toast";
import { colors, radius, shadow } from "@/src/theme";

const challenges = [{ id: "healthy-7", icon: "leaf" as const, title: "7 Days Healthy Eating", detail: "Log balanced meals for seven days", color: colors.green }, { id: "weight-loss-30", icon: "trending-down" as const, title: "30 Day Weight Goal", detail: "Build a consistent calorie routine", color: colors.peach }, { id: "water-14", icon: "water" as const, title: "14 Days Hydrated", detail: "Meet your daily water target", color: "#62A9D9" }];

export default function ChallengesScreen() {
  const [joined, setJoined] = useState<string[]>([]); const [message, setMessage] = useState("");
  const join = async (id: string, title: string) => { try { await api("/challenges", { method: "POST", body: JSON.stringify({ challenge_id: id }) }); setJoined((current) => [...new Set([...current, id])]); setMessage(`${title} joined`); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not join challenge"); } };
  return <AppScreen testID="challenges-screen"><View style={styles.header}><PressableScale style={styles.back} onPress={() => router.back()} testID="challenges-back-button"><Ionicons name="arrow-back" size={21} color={colors.ink} /></PressableScale><Text style={styles.headerTitle}>Challenges</Text><View style={styles.back} /></View><View style={styles.hero}><View style={styles.trophy}><Ionicons name="trophy" size={34} color={colors.peach} /></View><Text style={styles.heroTitle}>Small wins. Real change.</Text><Text style={styles.heroText}>Pick a challenge, build your streak, and collect badges along the way.</Text></View>{challenges.map((challenge) => <View key={challenge.id} style={styles.card} testID={`challenge-${challenge.id}`}><View style={[styles.icon, { backgroundColor: `${challenge.color}20` }]}><Ionicons name={challenge.icon} size={24} color={challenge.color} /></View><View style={styles.copy}><Text style={styles.title}>{challenge.title}</Text><Text style={styles.detail}>{challenge.detail}</Text><View style={styles.badge}><Ionicons name="flame" size={12} color={challenge.color} /><Text style={[styles.badgeText, { color: challenge.color }]}>0 day streak</Text></View></View><PressableScale style={[styles.join, joined.includes(challenge.id) && styles.joined]} onPress={() => join(challenge.id, challenge.title)} disabled={joined.includes(challenge.id)} testID={`join-challenge-${challenge.id}-button`}><Text style={styles.joinText}>{joined.includes(challenge.id) ? "Joined" : "Join"}</Text></PressableScale></View>)}<Toast visible={!!message} message={message} error={message.startsWith("Could")} onClose={() => setMessage("")} /></AppScreen>;
}

const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 44, height: 44, borderRadius: 17, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center" }, headerTitle: { color: colors.ink, fontSize: 17, fontWeight: "800" }, hero: { alignItems: "center", gap: 10, paddingVertical: 12 }, trophy: { width: 70, height: 70, borderRadius: 26, backgroundColor: colors.peachSoft, alignItems: "center", justifyContent: "center" }, heroTitle: { color: colors.ink, fontSize: 27, fontWeight: "900" }, heroText: { color: colors.muted, fontSize: 13, lineHeight: 20, textAlign: "center", maxWidth: 300 }, card: { flexDirection: "row", alignItems: "center", gap: 13, backgroundColor: colors.surface, borderRadius: radius.md, padding: 15, ...shadow }, icon: { width: 52, height: 52, borderRadius: 19, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, gap: 4 }, title: { color: colors.ink, fontSize: 15, fontWeight: "800" }, detail: { color: colors.muted, fontSize: 11, lineHeight: 16 }, badge: { flexDirection: "row", alignItems: "center", gap: 4 }, badgeText: { fontSize: 9, fontWeight: "800" }, join: { height: 36, paddingHorizontal: 13, borderRadius: 18, backgroundColor: colors.dark, justifyContent: "center" }, joined: { backgroundColor: colors.green }, joinText: { color: "white", fontSize: 11, fontWeight: "800" } });
