import { Ionicons } from "@expo/vector-icons";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { StyleSheet, Text, View } from "react-native";

import { api } from "@/src/api";
import { AppScreen } from "@/src/components/AppScreen";
import { PressableScale } from "@/src/components/PressableScale";
import { Toast } from "@/src/components/Toast";
import { colors, radius } from "@/src/theme";

const hours = [10, 11, 12, 13, 18, 19, 20, 21];

export default function FastingScreen() {
  const [start, setStart] = useState(12); const [end, setEnd] = useState(20); const [enabled, setEnabled] = useState(false); const [message, setMessage] = useState("");
  useFocusEffect(useCallback(() => { api<{ start_hour: number; end_hour: number; enabled: boolean }>("/fasting").then((data) => { setStart(data.start_hour); setEnd(data.end_hour); setEnabled(data.enabled); }).catch(() => undefined); }, []));
  const status = useMemo(() => { const now = new Date(); const hour = now.getHours() + now.getMinutes() / 60; const eating = start < end ? hour >= start && hour < end : hour >= start || hour < end; const target = eating ? end : start; let diff = target - hour; if (diff < 0) diff += 24; return { eating, hours: Math.floor(diff), minutes: Math.round((diff % 1) * 60) }; }, [start, end]);
  const save = async () => { try { await api("/fasting", { method: "PUT", body: JSON.stringify({ start_hour: start, end_hour: end, enabled: !enabled }) }); setEnabled(!enabled); setMessage(!enabled ? "Fasting schedule started" : "Fasting schedule paused"); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not update schedule"); } };
  return <AppScreen testID="fasting-screen"><View style={styles.header}><PressableScale style={styles.back} onPress={() => router.back()} testID="fasting-back-button"><Ionicons name="arrow-back" size={21} color={colors.ink} /></PressableScale><Text style={styles.headerTitle}>Intermittent fasting</Text><View style={styles.back} /></View><View style={styles.timer}><View style={styles.ring}><Text style={styles.status}>{status.eating ? "EATING WINDOW" : "FASTING"}</Text><Text style={styles.time}>{String(status.hours).padStart(2, "0")}:{String(status.minutes).padStart(2, "0")}</Text><Text style={styles.until}>until {status.eating ? "fast begins" : "window opens"}</Text></View></View><Text style={styles.label}>EATING WINDOW START</Text><View style={styles.hourRow}>{hours.slice(0,4).map((hour) => <PressableScale key={hour} style={[styles.hour, start === hour && styles.hourActive]} onPress={() => setStart(hour)} testID={`fasting-start-${hour}`}><Text style={[styles.hourText, start === hour && styles.hourTextActive]}>{hour > 12 ? hour - 12 : hour} {hour >= 12 ? "PM" : "AM"}</Text></PressableScale>)}</View><Text style={styles.label}>EATING WINDOW END</Text><View style={styles.hourRow}>{hours.slice(4).map((hour) => <PressableScale key={hour} style={[styles.hour, end === hour && styles.hourActive]} onPress={() => setEnd(hour)} testID={`fasting-end-${hour}`}><Text style={[styles.hourText, end === hour && styles.hourTextActive]}>{hour - 12} PM</Text></PressableScale>)}</View><View style={styles.summary}><Ionicons name="time" size={21} color={colors.peach} /><Text style={styles.summaryText}>{(24 - ((end - start + 24) % 24)) || 16} hour fast · {((end - start + 24) % 24) || 8} hour eating window</Text></View><PressableScale style={[styles.primary, enabled && styles.pause]} onPress={save} testID="toggle-fasting-button"><Text style={styles.primaryText}>{enabled ? "Pause schedule" : "Start schedule"}</Text></PressableScale><Toast visible={!!message} message={message} error={message.startsWith("Could")} onClose={() => setMessage("")} /></AppScreen>;
}

const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 44, height: 44, borderRadius: 17, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center" }, headerTitle: { color: colors.ink, fontSize: 17, fontWeight: "800" }, timer: { alignItems: "center", paddingVertical: 12 }, ring: { width: 220, height: 220, borderRadius: 110, borderWidth: 15, borderColor: colors.peach, alignItems: "center", justifyContent: "center", backgroundColor: colors.surface }, status: { color: colors.peach, fontSize: 10, letterSpacing: 1.5, fontWeight: "800" }, time: { color: colors.ink, fontSize: 43, fontWeight: "900", marginVertical: 5 }, until: { color: colors.muted, fontSize: 11 }, label: { color: colors.muted, fontSize: 10, letterSpacing: 1.3, fontWeight: "800" }, hourRow: { flexDirection: "row", gap: 8 }, hour: { flex: 1, height: 44, borderRadius: 16, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, alignItems: "center", justifyContent: "center" }, hourActive: { backgroundColor: colors.dark, borderColor: colors.dark }, hourText: { color: colors.muted, fontSize: 11, fontWeight: "700" }, hourTextActive: { color: "white" }, summary: { flexDirection: "row", gap: 9, alignItems: "center", justifyContent: "center", backgroundColor: colors.surface, padding: 14, borderRadius: radius.md }, summaryText: { color: colors.ink, fontSize: 12, fontWeight: "700" }, primary: { height: 56, borderRadius: radius.pill, backgroundColor: colors.dark, alignItems: "center", justifyContent: "center" }, pause: { backgroundColor: colors.peach }, primaryText: { color: "white", fontSize: 16, fontWeight: "800" } });
