import { Ionicons } from "@expo/vector-icons";
import * as Notifications from "expo-notifications";
import { router } from "expo-router";
import { useState } from "react";
import { Platform, StyleSheet, Switch, Text, View } from "react-native";

import { AppScreen } from "@/src/components/AppScreen";
import { PermissionSheet } from "@/src/components/PermissionSheet";
import { PressableScale } from "@/src/components/PressableScale";
import { Toast } from "@/src/components/Toast";
import { colors, radius, shadow } from "@/src/theme";

const defaults = { water: false, lunch: false, calories: false };

export default function RemindersScreen() {
  const [settings, setSettings] = useState(defaults);
  const [showPermission, setShowPermission] = useState(false);
  const [blocked, setBlocked] = useState(false);
  const [pendingKey, setPendingKey] = useState<keyof typeof defaults | null>(null);
  const [message, setMessage] = useState("");
  const requestIntent = async (key: keyof typeof defaults) => { if (settings[key]) { setSettings((s) => ({ ...s, [key]: false })); await Notifications.cancelAllScheduledNotificationsAsync(); return; } const status = await Notifications.getPermissionsAsync(); if (!status.granted) { setPendingKey(key); setBlocked(status.canAskAgain === false); setShowPermission(true); return; } await enable(key); };
  const grant = async () => { setShowPermission(false); if (Platform.OS === "android") await Notifications.setNotificationChannelAsync("calsnap-reminders", { name: "CalSnap reminders", importance: Notifications.AndroidImportance.DEFAULT }); const result = await Notifications.requestPermissionsAsync(); setBlocked(result.canAskAgain === false); if (result.granted && pendingKey) await enable(pendingKey); else setShowPermission(true); };
  const enable = async (key: keyof typeof defaults) => { const content = key === "water" ? { title: "Hydration check", body: "A glass of water now keeps your day on track." } : key === "lunch" ? { title: "Lunch check-in", body: "Log lunch now for a clearer daily picture." } : { title: "Daily nutrition check", body: "See how many calories and macros remain today." }; const hour = key === "water" ? 10 : key === "lunch" ? 13 : 19; await Notifications.scheduleNotificationAsync({ content, trigger: { type: Notifications.SchedulableTriggerInputTypes.DAILY, hour, minute: 0, channelId: "calsnap-reminders" } }); setSettings((s) => ({ ...s, [key]: true })); setMessage("Reminder scheduled"); setPendingKey(null); };
  return <AppScreen testID="reminders-screen"><View style={styles.header}><PressableScale style={styles.back} onPress={() => router.back()} testID="reminders-back-button"><Ionicons name="arrow-back" size={21} color={colors.ink} /></PressableScale><Text style={styles.headerTitle}>Smart reminders</Text><View style={styles.back} /></View><View style={styles.hero}><View style={styles.bell}><Ionicons name="notifications" size={28} color={colors.peach} /></View><Text style={styles.heroTitle}>Gentle nudges, right on time.</Text><Text style={styles.heroText}>Choose only the reminders that support your routine.</Text></View><ReminderRow icon="water" title="Water reminder" detail="Every day at 10:00 AM" value={settings.water} onChange={() => requestIntent("water")} testID="water-reminder-switch" /><ReminderRow icon="restaurant" title="Lunch check-in" detail="Every day at 1:00 PM" value={settings.lunch} onChange={() => requestIntent("lunch")} testID="lunch-reminder-switch" /><ReminderRow icon="pie-chart" title="Calories remaining" detail="Daily progress at 7:00 PM" value={settings.calories} onChange={() => requestIntent("calories")} testID="calorie-reminder-switch" /><View style={styles.note}><Ionicons name="information-circle" size={18} color={colors.greenDark} /><Text style={styles.noteText}>Notifications are scheduled on this device. Turning one off clears scheduled CalSnap reminders.</Text></View><PermissionSheet visible={showPermission} kind="notifications" blocked={blocked} onContinue={grant} onClose={() => setShowPermission(false)} /><Toast visible={!!message} message={message} onClose={() => setMessage("")} /></AppScreen>;
}

function ReminderRow({ icon, title, detail, value, onChange, testID }: { icon: keyof typeof Ionicons.glyphMap; title: string; detail: string; value: boolean; onChange: () => void; testID: string }) { return <View style={styles.row}><View style={styles.icon}><Ionicons name={icon} size={21} color={colors.greenDark} /></View><View style={styles.copy}><Text style={styles.title}>{title}</Text><Text style={styles.detail}>{detail}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{ false: "#D9D8D3", true: colors.green }} thumbColor="white" testID={testID} /></View>; }

const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 44, height: 44, borderRadius: 17, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center" }, headerTitle: { color: colors.ink, fontSize: 17, fontWeight: "800" }, hero: { alignItems: "center", gap: 9, paddingVertical: 14 }, bell: { width: 64, height: 64, borderRadius: 23, backgroundColor: colors.peachSoft, alignItems: "center", justifyContent: "center" }, heroTitle: { color: colors.ink, fontSize: 25, fontWeight: "900", textAlign: "center" }, heroText: { color: colors.muted, fontSize: 13, textAlign: "center" }, row: { minHeight: 78, flexDirection: "row", alignItems: "center", gap: 13, backgroundColor: colors.surface, padding: 15, borderRadius: radius.md, ...shadow }, icon: { width: 44, height: 44, borderRadius: 16, backgroundColor: colors.greenSoft, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, gap: 4 }, title: { color: colors.ink, fontSize: 15, fontWeight: "800" }, detail: { color: colors.muted, fontSize: 11 }, note: { flexDirection: "row", alignItems: "flex-start", gap: 9, backgroundColor: colors.greenSoft, borderRadius: radius.md, padding: 14 }, noteText: { flex: 1, color: colors.muted, fontSize: 11, lineHeight: 17 } });
