import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Image, StyleSheet, Text, View } from "react-native";

import { api } from "@/src/api";
import { AppScreen } from "@/src/components/AppScreen";
import { MetricCard } from "@/src/components/NutritionUi";
import { PressableScale } from "@/src/components/PressableScale";
import { Toast } from "@/src/components/Toast";
import { colors, radius, shadow } from "@/src/theme";
import type { Meal } from "@/src/types";

export default function MealDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [meal, setMeal] = useState<Meal | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  useEffect(() => { api<Meal>(`/meals/${id}`).then(setMeal).catch(() => setMeal(null)).finally(() => setLoading(false)); }, [id]);
  const repeat = async () => { if (!meal) return; try { await api("/meals", { method: "POST", body: JSON.stringify({ meal_type: meal.meal_type, title: meal.title, eaten_at: new Date().toISOString(), items: meal.items, source: "history" }) }); setMessage("Meal added to today"); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not repeat meal"); } };
  const remove = async () => { if (!meal) return; try { await api(`/meals/${meal.meal_id}`, { method: "DELETE" }); router.replace("/(tabs)/history"); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not delete meal"); } };
  if (loading) return <AppScreen><ActivityIndicator color={colors.peach} /></AppScreen>;
  if (!meal) return <AppScreen><Text style={styles.title}>Meal not found</Text></AppScreen>;
  return <AppScreen testID="meal-detail-screen"><View style={styles.header}><PressableScale style={styles.back} onPress={() => router.back()} testID="meal-detail-back-button"><Ionicons name="arrow-back" size={21} color={colors.ink} /></PressableScale><Text style={styles.headerTitle}>Meal details</Text><PressableScale style={styles.back} onPress={remove} testID="delete-meal-button"><Ionicons name="trash-outline" size={20} color={colors.red} /></PressableScale></View><View style={styles.hero}>{meal.image_base64 || meal.thumbnail_base64 ? <Image source={{ uri: `data:image/jpeg;base64,${meal.image_base64 ?? meal.thumbnail_base64}` }} style={styles.mealPhoto} resizeMode="cover" testID="meal-detail-photo" /> : <View style={styles.mealIcon}><Ionicons name="restaurant" size={30} color={colors.peach} /></View>}<Text style={styles.kicker}>{meal.meal_type.toUpperCase()} • {new Date(meal.eaten_at).toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}</Text><Text style={styles.title}>{meal.title}</Text><Text style={styles.calories}>{Math.round(meal.totals.calories)} kcal</Text></View><View style={styles.metrics}><MetricCard icon="fitness" label="Protein" value={`${Math.round(meal.totals.protein_g)}g`} /><MetricCard icon="leaf" label="Carbs" value={`${Math.round(meal.totals.carbs_g)}g`} accent={colors.yellow} /><MetricCard icon="water" label="Fat" value={`${Math.round(meal.totals.fat_g)}g`} accent={colors.peach} /></View><Text style={styles.section}>Foods</Text>{meal.items.map((item) => <View key={item.item_id} style={styles.food}><View><Text style={styles.foodName}>{item.name}</Text><Text style={styles.foodDetail}>{item.portion} · {Math.round(item.estimated_weight_g)}g · {Math.round(item.confidence * 100)}% confidence</Text></View><Text style={styles.foodCalories}>{Math.round(item.calories)} kcal</Text></View>)}<PressableScale style={styles.repeat} onPress={repeat} testID="repeat-meal-button"><Ionicons name="repeat" size={20} color="white" /><Text style={styles.repeatText}>Add again today</Text></PressableScale><Toast visible={!!message} message={message} error={message.startsWith("Could")} onClose={() => setMessage("")} /></AppScreen>;
}

const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 44, height: 44, borderRadius: 17, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center", ...shadow }, headerTitle: { color: colors.ink, fontSize: 17, fontWeight: "800" }, hero: { alignItems: "center", gap: 7, paddingVertical: 10 }, mealIcon: { width: 68, height: 68, borderRadius: 24, backgroundColor: colors.peachSoft, alignItems: "center", justifyContent: "center" }, mealPhoto: { width: 148, height: 148, borderRadius: 28, backgroundColor: colors.peachSoft, ...shadow }, kicker: { color: colors.muted, fontSize: 10, letterSpacing: 1.2, fontWeight: "800", marginTop: 6 }, title: { color: colors.ink, fontSize: 27, fontWeight: "900", textAlign: "center" }, calories: { color: colors.peach, fontSize: 18, fontWeight: "900" }, metrics: { flexDirection: "row", gap: 9 }, section: { color: colors.ink, fontSize: 20, fontWeight: "900" }, food: { minHeight: 66, backgroundColor: colors.surface, borderRadius: radius.md, padding: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, ...shadow }, foodName: { color: colors.ink, fontSize: 15, fontWeight: "800" }, foodDetail: { color: colors.muted, fontSize: 10, marginTop: 4 }, foodCalories: { color: colors.ink, fontSize: 13, fontWeight: "800" }, repeat: { height: 56, borderRadius: radius.pill, backgroundColor: colors.dark, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 9 }, repeatText: { color: "white", fontSize: 15, fontWeight: "800" } });
